### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by chomyeong** [sitepoint/Rauth#10]
Hi bro, i'm very like your project,but when i install it ,I get the error.  What can i do ? thanks!
  [InvalidArgumentException]
  Could not find package sitepoint/rauth at any version matching your PHP version 5.5.10.0

**Comment by Swader** [comment]
As described in the readme, the minimum PHP version for this project is 7.0.

**Comment by chomyeong** [comment]
oh,I'm very sorry! thank you for your answer, bro!:D
